package game.items;

import edu.monash.fit2099.engine.actions.Action;
import edu.monash.fit2099.engine.items.Item;
import edu.monash.fit2099.engine.positions.Exit;
import edu.monash.fit2099.engine.positions.GameMap;
import edu.monash.fit2099.engine.positions.Location;
import edu.monash.fit2099.engine.statistics.BaseStatistic;
import game.actions.DepositAction;
import game.actions.SellAction;
import game.effects.SlimeSpawnEffect;
import game.enemies.Slime;
import game.enums.ItemStatistics;
import game.grounds.Supercomputer;
import game.interfaces.Depositable;
import game.interfaces.Sellable;
import game.loaders.ContractedWorker;

/**
 * A large industrial fan that can be sold or deposited at a Supercomputer.
 * Selling it may disrupt the cooling system and spawn a Slime, while
 * depositing it provides healing to the worker.
 * @author Heesu Kim
 */
public class IndustrialFan extends Item implements Sellable, Depositable {

    /**
     * Credits received when selling the Industrial Fan.
     */
    private static final int SELL_PRICE = 150;

    /**
     * Company credits earned when depositing the Industrial Fan.
     */
    private static final int DEPOSIT_VALUE = 10;

    /**
     * Weight of the Industrial Fan.
     */
    private static final int WEIGHT = 5;

    /**
     * Amount of health restored when the fan is deposited.
     */
    private static final int HEAL_AMOUNT = 10;

    /**
     * Constructor of the IndustrialFan class.
     */
    public IndustrialFan() {
        super("Industrial Fan", '@');
        this.addNewStatistic(ItemStatistics.WEIGHT, new BaseStatistic(WEIGHT));
        this.addNewStatistic(ItemStatistics.SELLABLE, new BaseStatistic(1));
        this.addNewStatistic(ItemStatistics.DEPOSITABLE, new BaseStatistic(1));
        this.makePortable();
    }

    /**
     * Returns the sell price of the Industrial Fan.
     *
     * @return the sell price
     */
    @Override
    public int getSellPrice() {
        return SELL_PRICE;
    }

    /**
     * Applies the effect of selling the Industrial Fan.
     * Removing the fan may cause a Slime to spawn beside the Supercomputer.
     *
     * @param worker the worker selling the fan
     * @param map the map where the action occurs
     * @param supercomputerLocation the location of the Supercomputer
     * @return a description of the sell outcome
     */
    @Override
    public String onSell(ContractedWorker worker, GameMap map, Location supercomputerLocation) {
        Slime slime = new Slime();

        for (Exit exit : supercomputerLocation.getExits()) {
            Location destination = exit.getDestination();

            if (!destination.containsAnActor() && destination.canActorEnter(slime)) {
                try {
                    map.addActor(slime, destination);
                    new SlimeSpawnEffect().applySpawnEffect(slime, destination);
                    return "A Slime spawns beside the Supercomputer after the cooling system is stripped.";
                } catch (Exception e) {
                    return "The cooling system shudders, but the Slime could not spawn.";
                }
            }
        }

        return "The cooling system shudders, but there is no empty adjacent tile for a Slime.";
    }

    /**
     * Returns the sell action associated with this Industrial Fan.
     *
     * @param worker the worker performing the action
     * @param supercomputerLocation the location of the Supercomputer
     * @return a SellAction for this Industrial Fan
     */
    @Override
    public Action getSellAction(ContractedWorker worker, Location supercomputerLocation) {
        return new SellAction(worker, this, this, supercomputerLocation);
    }

    /**
     * Returns the company credit value of the Industrial Fan.
     *
     * @return the deposit value
     */
    @Override
    public int getDepositValue() {
        return DEPOSIT_VALUE;
    }

    /**
     * Applies the effect of depositing the Industrial Fan.
     * The worker is healed by the fresh airflow generated by the fan.
     *
     * @param worker the worker depositing the fan
     * @param map the map where the action occurs
     * @param supercomputerLocation the location of the Supercomputer
     * @return a description of the deposit outcome
     */
    @Override
    public String onDeposit(ContractedWorker worker, GameMap map, Location supercomputerLocation) {
        worker.heal(HEAL_AMOUNT);

        return "Fresh oxygen rushes from the ventilation override. "
                + worker + " heals " + HEAL_AMOUNT + " HP.";
    }

    /**
     * Returns the deposit action associated with this Industrial Fan.
     *
     * @param worker the worker performing the action
     * @param supercomputer the Supercomputer receiving the deposit
     * @param supercomputerLocation the location of the Supercomputer
     * @return a DepositAction for this Industrial Fan
     */
    @Override
    public Action getDepositAction(ContractedWorker worker, Supercomputer supercomputer,
                                   Location supercomputerLocation) {
        return new DepositAction(worker, this, supercomputer, supercomputerLocation);
    }
}